default_language_version:
  python: python3.10
default_stages: [commit, push, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: fix-encoding-pragma
      args: [--remove]
      files: '.*\.py$'
    - id: requirements-txt-fixer
      files: 'requirements\..*\.txt$'
      stages: [push, manual]
    - id: check-toml
      files: '.*\.toml$'

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
      args: [--config=pyproject.toml]
      files: '.*\.py$'

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: [--config=pyproject.toml]
      additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/jazzband/pip-tools
    rev: "7.3.0"
    hooks:
      - id: pip-compile
        files: 'requirements\.txt$'
        args: ["--output-file=requirements.lock.txt", "--no-emit-index-url", "requirements.txt"]
