version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./ci/dockerfiles/Dockerfile
    entrypoint: ./ci/entrypoint.sh fastapi-dev
    # env_file:
    #   - .env
    volumes:
      - .:/srv
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: always
    # depends_on:
    #   - mongodb
    networks:
      - app-network
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  # mongodb:
  #   image: mongo:7.0
  #   env_file:
  #     - .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo_data:/data/db
  #   networks:
  #     - app-network

  # redis:
  #   image: redis:7-alpine

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # mongo_data:
  minio_data:
