[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.poetry]
name = "WordParser"
version = "0.1.0"
description = "App to parse word's docs to flashcards"
license = "MIT"
authors = ["Wojciech Ziarnik <woj.ziarnik@gmail.com>" , "Dawid Adamczyk"]
