# Generated by Django 4.1 on 2022-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Category of flashcards.', max_length=30, unique=True)),
                ('title', models.CharField(help_text='Title of flashcard.', max_length=50, unique=True)),
                ('content', models.TextField(help_text='Content (reverse) of flashcard.', unique=True)),
            ],
        ),
    ]
