# Generated by Django 4.1 on 2022-08-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_flashcard_category_alter_flashcard_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Category of flashcards.', max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.flashcardcategory'),
        ),
    ]
