# Generated by Django 4.1 on 2022-08-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_flashcardcategory_alter_flashcard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
