# Generated by Django 4.1 on 2022-08-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_flashcardcategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardcategory',
            old_name='category',
            new_name='name',
        ),
    ]
