# Generated by Django 4.1 on 2022-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_rename_category_flashcardcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='content',
            field=models.TextField(help_text='Content (reverse) of flashcard.'),
        ),
    ]
