# Generated by Django 4.1 on 2022-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_alter_flashcard_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='content',
            field=models.TextField(help_text='Content (reverse) of flashcard.', unique=True),
        ),
    ]
