# Generated by Django 4.1 on 2022-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_alter_flashcard_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='content',
            field=models.TextField(help_text='Content (reverse) of flashcard.'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='title',
            field=models.CharField(help_text='Title of flashcard.', max_length=50, unique=True),
        ),
    ]
