# Generated by Django 4.1 on 2022-09-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_alter_flashcard_content_alter_flashcard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='known',
            field=models.BooleanField(default=False, help_text='Status of flashcard.'),
        ),
    ]
