# Generated by Django 4.1 on 2022-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_flashcard_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='content',
            field=models.TextField(help_text='Content (reverse) of flashcard.'),
        ),
    ]
